import './globals.css'
import { Barlow_Condensed } from 'next/font/google'
import Navbar from "@/components/Navbar";

const barlow = Barlow_Condensed({ subsets: ["latin"] , weight:"300"});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={barlow.className} >
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
